## NumPy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [2]:
# Import library
import numpy as np

### Convert to Array

In [ ]:
# 1 dimension array
ls = [1,2,3,4,5]
arr = np.array(ls)
type(arr)

In [4]:
arr.shape

(5,)

In [11]:
# 2 dimension array
arr2 = np.array([[1,2,3,4],
                [5,6,7,8]])
arr2.shape

(2, 4)

In [14]:
# reshape 2D array
arr2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
arr2.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [16]:
# Convert touple into array
arr3 = np.array((1,2,3,4,5))
arr3

array([1, 2, 3, 4, 5])

In [19]:
arr3[1]

2

In [17]:
# Convert dictionary to array
dict = {1:'a',
2:'b',
3:'c'}

arr4 = np.array(dict)
arr4

array({1: 'a', 2: 'b', 3: 'c'}, dtype=object)

In [18]:
arr4.shape

()

In [21]:
arr4[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [24]:
# Create array from scratch
custom_array = np.arange(1,10)

In [25]:
# reshaping created array
custom_array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
range(1,10)

range(1, 10)

In [30]:
# interview question

# here 50 represent min value and 1 represent max value, so it wont print anything.
print(np.arange(50, 1))

# To print this in reverse order use the below format
print(np.arange(50, 1, -2))

[]
[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


### np.linspace() 
the method distributes range of values in given number of parts.


In [31]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

#### Create array with 0's and 1's

In [32]:
# arrays with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# create arrays with ones
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
# 3D array with ones
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

#### Broadcast operations

An operation getting applied to entire array

In [42]:
5 + np.ones((4,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

### Identity matrix
Diagonal elements in are 1 and other elemetns are 0

In [44]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Randomly generate numbers


In [45]:
# rand()
print("Random number generation (Uniform Destribution)")
np.random.rand(2,3)

Random number generation (Uniform Destribution)


array([[0.5262287 , 0.88169453, 0.19205862],
       [0.91358229, 0.29775177, 0.94705286]])

In [47]:
# randn()
print("Random number following (Normal Distribution) with mean=0 and std=1")

np.random.randn(5,3)

Random number following (Normal Distribution) with mean=0 and std=1


array([[ 0.07443483, -0.54292897, -0.8953412 ],
       [ 0.86531471,  1.25112604,  1.19170379],
       [-0.2590664 , -0.70171771,  0.246696  ],
       [ 0.97452635, -0.34254494,  0.37647857],
       [-2.07081216, -0.37597904,  1.16282683]])

In [52]:
# get one random number from the given range
np.random.randint(1,100)

92

In [54]:
# get N random number from the given range
np.random.randint(1,100, 10) # 10 random numbers

array([23, 85, 18, 26, 52, 15, 75, 75, 32, 70])

In [55]:
# get random number from the given range in the form of array

np.random.randint(1,100, (4,3))

array([[26,  1, 75],
       [30, 88, 70],
       [74, 59, 16],
       [62, 96,  6]])

### Slicing


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

In [65]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[3::-1] # Get reverse elemetns from 3rd position

array([4, 3, 2, 1])

In [69]:
arr[::-1] # reverse whole array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [71]:
arr[-3:-7:-1]

array([8, 7, 6, 5])

#### Slicing with 2D array


In [94]:
# arr_2d = np.random.randint(2,100,20).reshape(5,4)
arr_2d = np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16],
[17,18,19,20]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [95]:
arr_2d[0:3, 1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [96]:
arr_2d[3:, 1:4]

array([[14, 15, 16],
       [18, 19, 20]])

In [97]:
arr_2d[2:4, 2:4]

array([[11, 12],
       [15, 16]])

In [99]:
arr_2d[-3:-1, -2:]

array([[11, 12],
       [15, 16]])

In [ ]:
# PROBLEM STATEMENT
# Get numbers [13, 16]
#             [17, 20]

### Universal Function

In [102]:
# Example2
arr1 = np.random.randint(1,100,(3,3))
arr2 = np.random.randint(1,100,(3,3))

In [104]:
print(arr1)
print(arr2)

[[58 42 42]
 [87 69 21]
 [86 75 18]]
[[79 76 19]
 [55 85 42]
 [38 26  5]]


In [105]:
# Deviding arrays
arr1/arr2

array([[0.73417722, 0.55263158, 2.21052632],
       [1.58181818, 0.81176471, 0.5       ],
       [2.26315789, 2.88461538, 3.6       ]])

In [106]:
np.sqrt(arr1)

array([[7.61577311, 6.4807407 , 6.4807407 ],
       [9.32737905, 8.30662386, 4.58257569],
       [9.2736185 , 8.66025404, 4.24264069]])

In [110]:
np.dot(arr1,arr2)

array([[ 8488,  9070,  3076],
       [11466, 13023,  4656],
       [11603, 13379,  4874]])

: 

In [107]:
# Example2:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr3[5:] = 1000
print(arr3)

[   1    2    3    4    5 1000 1000 1000 1000]
